In [1]:
from typing import cast,Any,Coroutine
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import TargetEncoder,StandardScaler
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error
from sklearn.impute import KNNImputer
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
import seaborn as sns
from scipy.stats import stats
import re
import bs4
import httpx
import asyncio
import boto3
from botocore import client
import io
SEMAFORO=asyncio.Semaphore(20)
pd.set_option('display.max_columns',None)
K=1.5
url_principal:str='https://www.pisos.com'
headers={
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept-Language': 'es-ES,es;q=0.9',
}

In [ ]:
session=boto3.Session()
s3:client.BaseClient=session.client('s3')
df_desde_s3=pd.read_csv(io.BytesIO(s3.get_object(Bucket='dataframes-487825334013-eu-north-1-an',Key='datos_crudos.csv')['Body'].read()))
df_desde_s3

,nombre,precio,tipo,tipo_de_casa,superficie_util,conservacion,superficie_solar,planta,habitaciones,banhos,referencia,antiguedad,superficie_construida,adaptado_a_personas_con_movilidad_reducida,balcon,se_aceptan_mascotas,calle_alumbrada,calle_asfaltada,lavadero,ascensor,chimenea,cocina_equipada,exterior,armarios_empotrados,garaje,sistema_de_seguridad,piscina,comedor,luz,carpinteria_exterior,orientacion,calefaccion,amueblado,urbanizado,trastero,puerta_blindada,vidrios_dobles,telefono,interior,soleado,agua,portero_automatico,aire_acondicionado,tipo_suelo,jardin,carpinteria_interior,terraza,gastos_de_comunidad,gas,precio_superficie,consumo,emisiones,descripcion,baños,antigüedad
0,apartamento-abrantes-65041026653_100500,295000.0,apartamento,NaN,74.0,En buen estado,NaN,3ª,3.0,1.0,ABR/9927,Más de 50 años,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,1,NaN,NaN,NaN,NaN,Otra compañía,NaN,Este,Gas natural,NaN,NaN,True,True,NaN,True,True,True,True,NaN,True,Parquet,NaN,True,NaN,Entre 20 y 40 €,NaN,3687.0,NaN,NaN,\n\t\t\t\t**Piso exterior muy luminoso junto a...,NaN,NaN
1,apartamento-acacias28005-63376212013_109800,560000.0,apartamento,NaN,57.0,En buen estado,NaN,Bajo,2.0,1.0,23340459,Más de 50 años,60.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,True,Entre 80 y 100 €,NaN,9333.0,NaN,NaN,\n\t\t\t\tMuy buena ubicación a cinco minutos ...,NaN,NaN
2,apartamento-acacias28005-63421570468_105600,495000.0,apartamento,NaN,NaN,NaN,NaN,NaN,3.0,2.0,VM2511091,NaN,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6600.0,NaN,NaN,\n\t\t\t\tEstupendo dúplex en Arganzuela refor...,NaN,NaN
3,apartamento-adelfas28007-63427703595_105600,699000.0,apartamento,NaN,NaN,NaN,NaN,NaN,3.0,3.0,VM2510063,NaN,116.0,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6025.0,NaN,NaN,\n\t\t\t\tAProperties presenta este precioso p...,NaN,NaN
4,apartamento-adelfas28007-65928881028_105600,530000.0,apartamento,NaN,NaN,NaN,NaN,NaN,1.0,1.0,VM2607043,NaN,91.0,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5824.0,NaN,NaN,\n\t\t\t\tPresentamos una excelente oportunida...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15911,apartamento-jeronimos-66686496259_100500,1990000.0,apartamento,NaN,NaN,En buen estado,NaN,Bajo,2.0,NaN,EXP15558/8930,NaN,194.0,True,True,NaN,NaN,NaN,True,True,NaN,NaN,NaN,NaN,1,NaN,Comunitaria,NaN,Otra compañía,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True,True,True,True,NaN,True,NaN,NaN,NaN,True,Más de 100 €,NaN,10257.0,NaN,NaN,\n\t\t\t\tEn primera línea del paseo marítimo ...,3.0,Menos de 5 años
15912,piso-lista_barrio28006-66690479426_108900,1299000.0,piso,NaN,NaN,NaN,NaN,1ª,NaN,NaN,INM55604,NaN,139.0,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True,NaN,True,NaN,True,NaN,True,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,True,NaN,True,9345.0,NaN,NaN,\n\t\t\t\tHay pisos en el Barrio de Salamanca....,NaN,NaN
15913,piso-villaverde_san_andres-66699046690_100200,180000.0,piso,NaN,NaN,En buen estado,NaN,1ª,3.0,NaN,668336,NaN,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,2727.0,225.0,225.0,\n\t\t\t\tAgencia inmobiliaria de madrid - zon...,1.0,Más de 50 años
15914,apartamento-ciudalcampo_fuente_del_fresno28703...,210000.0,apartamento,NaN,45.0,En buen estado,NaN,1ª,1.0,NaN,N06-BAD-00160,NaN,48.0,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,True,NaN,True,NaN,NaN,NaN,NaN,Eléctrica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,4375.0,NaN,NaN,\n\t\t\t\tOPORTUNIDAD PARA INVERSORES Y EMPREN...,1.0,NaN
15915,piso-puente_de_vallecas_san_diego28053-6675395...,286000.0,piso,NaN,50.0,A reformar,NaN,2ª,2.0,NaN,SanDi,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Independiente,True,NaN,NaN,NaN,NaN,NaN,NaN,Aluminio,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Frío,Gres,NaN,NaN,Dos con dos orientaciones diferentes,NaN,NaN,4766.0,271.0,53.0,"\n\t\t\t\tPiso en San Diego, Madrid - ¡Oportun...",1.0,Más de 50 años

In [3]:
def nombres_json(x:str):
    return x.replace(' ','_').lower().replace('á','a').replace('é','e').replace('í','i').replace('ó','o').replace('ú','u')
caracteristicas_especificables=['Lavadero','Ascensor','Chimenea','Cocina equipada','Exterior','Armarios empotrados','Garaje','Sistema de seguridad','Piscina','Comedor','Luz','Carpintería exterior','Orientación','Calefacción','Amueblado','Urbanizado','Trastero','Puerta blindada','Vidrios dobles','Teléfono','Interior','Soleado','Agua','Portero automático','Aire acondicionado','Tipo suelo','Jardín','Carpintería interior','Terraza','Gastos de comunidad','Gas']
caracteristicas_especificables_json=list(map(nombres_json,caracteristicas_especificables))
booleanos=['Adaptado a personas con movilidad reducida','Balcón','Se aceptan mascotas','Calle alumbrada','No se aceptan mascotas','Calle asfaltada']
booleanos_json=list(map(nombres_json,booleanos))
no_booleanos=['Tipo de casa','Superficie útil','Conservación','Superficie solar','Planta','Habitaciones','Baños','Referencia','Antigüedad','Superficie construida']
no_booleanos_json=list(map(nombres_json,no_booleanos))
async def jsonear(v:bs4.Tag)->dict[str,Any]:
    json:dict[str,Any]={}
    json['nombre']=str(cast(bs4.Tag,v.find(class_='js-share'))['data-url']).replace(f'{url_principal}/comprar/','').replace('/','')
    posible_precio=str(cast(bs4.Tag,v.find(class_='jsPriceValue')).text).split(' ')[0].replace('.','').replace(',','.')
    json['precio']=None if not len(re.findall("\\d",posible_precio))==len(posible_precio.replace('.','')) else float(posible_precio)
    json['tipo']=json['nombre'].split('-')[0]
    precio_superficie:float | None=None
    consumo:float | None=None
    emisiones:float | None=None
    descripcion:str | None=None
    div_caracteristicas:bs4.Tag=cast(bs4.Tag,v.find(class_='features-container'))
    for nb,nbj in zip(no_booleanos,no_booleanos_json):
        value=None
        posible=div_caracteristicas.find('span',class_='features__label',string=f"{nb}: ")
        if confirmado:=posible:
            value=cast(bs4.Tag,confirmado.find_next_sibling('span')).text
            if 'superficie' in nbj:
                value=float(value.split(' ')[0].replace('.','').replace(',','.'))
            if nbj in ['habitaciones','banhos']:
                value=int(value)
        json[nbj]=value
    for b,bj in zip(booleanos,booleanos_json):
        posible=div_caracteristicas.find(class_='features__label',string=b)
        if posible:
            if bj=='no_se_aceptan_mascotas':
                json['se_aceptan_mascotas']=False
            else:
                json[bj]=True
        else:
            if bj!='no_se_aceptan_mascotas':
                if bj!='se_aceptan_mascotas' or not 'se_aceptan_mascotas' in json.keys():
                    json[bj]=None
    for e,ej in zip(caracteristicas_especificables,caracteristicas_especificables_json):
        value=None
        for sufijo in ['',': ']:
            posible=div_caracteristicas.find('span',class_='features__label',string=f"{e}{sufijo}")
            if confirmado:=posible:
                value=True
                if confirmado:=confirmado.find_next_sibling('span'):
                    value=confirmado.text
        json[ej]=value
    
    posible_ps=v.find('li',class_='features-summary__item',string=re.compile('€/m²'))
    posible_consumo=v.find('span',string=re.compile('kWh/m²'))
    posible_emisiones=v.find('span',string=re.compile('CO₂/m²'))
    posible_desc=v.find(class_='description__content')
    
    if confirmado:=posible_ps:
        precio_superficie=float(confirmado.text.split(' ')[0].replace('.','').replace(',','.'))
    if confirmado:=posible_consumo:
        consumo=float(confirmado.text.split(' ')[0].replace('.','').replace(',','.'))
    if confirmado:=posible_emisiones:
        emisiones=float(confirmado.text.split(' ')[0].replace('.','').replace(',','.'))
    if confirmado:=posible_desc:
        descripcion=confirmado.text
    
    return {
        **json,
        'precio_superficie':precio_superficie,
        'consumo':consumo,
        'emisiones':emisiones,
        'descripcion':descripcion,
    }
async def sacar_jsons(lista:list[bs4.Tag])->list[dict[str,Any]]:
    tareas:list[Coroutine[Any,Any,dict[str,Any]]]=[jsonear(x) for x in lista]
    tareas_completas:list[dict[str,Any]]=await asyncio.gather(*tareas)
    return tareas_completas

In [4]:
df_crudo:pd.DataFrame=pd.read_csv('./datos_crudos.csv')
ads_nuevos:list[bs4.Tag]=[]
async def sacar_ad(client:httpx.AsyncClient,url:str)->str:
    async with SEMAFORO:
        response:httpx.Response=await client.get(f'{url_principal}{url}',timeout=10,headers=headers)
        return response.text
fin:bool=False
async with httpx.AsyncClient(transport=httpx.AsyncHTTPTransport(retries=1),limits=httpx.Limits(max_connections=20,max_keepalive_connections=20)) as client:
    for page in range(1,101):
        if fin:
            break
        response=await client.get(url=f'{url_principal}/venta/pisos-madrid/fecharecientedesde-desc/{page}',timeout=10,headers=headers)
        lista=bs4.BeautifulSoup(response.text,'html.parser').find_all(class_='ad-preview')
        for ad in lista:
            if str(ad['data-lnk-href']).replace('/comprar/','').replace('/','') in df_crudo['nombre'].values:
                fin=True
                break
            else:
                ads_nuevos.append(ad)
    tareas:list[Coroutine[Any,Any,str]]=[sacar_ad(client,str(ad['data-lnk-href'])) for ad in ads_nuevos]
    htmls_nuevos:list[str]=await asyncio.gather(*tareas)
print(len(htmls_nuevos))

0

In [5]:
async def sacar_detalles(html:str)->bs4.Tag:
    parseado=bs4.BeautifulSoup(html,'html.parser')
    return cast(bs4.Tag,parseado.find(class_='details__col-right'))
async def sacar_detalles_htmls(htmls:list[str])->list[bs4.Tag]:
    tareas:list[Coroutine[Any,Any,bs4.Tag]]=[sacar_detalles(html) for html in htmls]
    return await asyncio.gather(*tareas)
nuevos=await sacar_detalles_htmls(htmls_nuevos)
details_json:list[dict[str,Any]]=await sacar_jsons(nuevos)
df_crudo=pd.concat([df_crudo,pd.DataFrame(details_json)],ignore_index=True)

In [ ]:
# df_crudo.to_csv('./datos_crudos.csv')

In [64]:
df:pd.DataFrame=pd.read_csv('./datos_crudos.csv')
df=df.assign(
    localidad=df['nombre'].map(lambda x:str(x).split('-')[1]),
    localidad_sin_numero=df['nombre'].map(lambda x:re.sub("\\d",'',str(x).split('-')[1])),
    cp=df['nombre'].map(lambda x:re.sub("[^0-9]",'',str(x).split('-')[1])).map(lambda x:x if len(str(x))==5 else np.nan),
    descripcion=df['descripcion'].map(lambda x:" ".join(str(x).replace('\n','. ').split()))
)
df

,nombre,precio,tipo,tipo_de_casa,superficie_util,conservacion,superficie_solar,planta,habitaciones,banhos,referencia,antiguedad,superficie_construida,adaptado_a_personas_con_movilidad_reducida,balcon,se_aceptan_mascotas,calle_alumbrada,calle_asfaltada,lavadero,ascensor,chimenea,cocina_equipada,exterior,armarios_empotrados,garaje,sistema_de_seguridad,piscina,comedor,luz,carpinteria_exterior,orientacion,calefaccion,amueblado,urbanizado,trastero,puerta_blindada,vidrios_dobles,telefono,interior,soleado,agua,portero_automatico,aire_acondicionado,tipo_suelo,jardin,carpinteria_interior,terraza,gastos_de_comunidad,gas,precio_superficie,consumo,emisiones,descripcion,localidad,localidad_sin_numero,cp
0,apartamento-abrantes-65041026653_100500,295000.0,apartamento,NaN,74.0,En buen estado,NaN,3ª,3.0,1.0,ABR/9927,Más de 50 años,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,1,NaN,NaN,NaN,NaN,Otra compañía,NaN,Este,Gas natural,NaN,NaN,True,True,NaN,True,True,True,True,NaN,True,Parquet,NaN,True,NaN,Entre 20 y 40 €,NaN,3687.0,NaN,NaN,. **Piso exterior muy luminoso junto al Metro ...,abrantes,abrantes,NaN
1,apartamento-acacias28005-63376212013_109800,560000.0,apartamento,NaN,57.0,En buen estado,NaN,Bajo,2.0,1.0,23340459,Más de 50 años,60.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,True,Entre 80 y 100 €,NaN,9333.0,NaN,NaN,. Muy buena ubicación a cinco minutos de Sol a...,acacias28005,acacias,28005
2,apartamento-acacias28005-63421570468_105600,495000.0,apartamento,NaN,NaN,NaN,NaN,NaN,3.0,2.0,VM2511091,NaN,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6600.0,NaN,NaN,. Estupendo dúplex en Arganzuela reformadoSe t...,acacias28005,acacias,28005
3,apartamento-adelfas28007-63427703595_105600,699000.0,apartamento,NaN,NaN,NaN,NaN,NaN,3.0,3.0,VM2510063,NaN,116.0,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6025.0,NaN,NaN,. AProperties presenta este precioso piso a es...,adelfas28007,adelfas,28007
4,apartamento-adelfas28007-65928881028_105600,530000.0,apartamento,NaN,NaN,NaN,NaN,NaN,1.0,1.0,VM2607043,NaN,91.0,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5824.0,NaN,NaN,. Presentamos una excelente oportunidad para i...,adelfas28007,adelfas,28007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15894,piso-zona_suroeste-65861155816_106600,265000.0,piso,NaN,84.0,Reformado,NaN,NaN,2.0,1.0,1167,NaN,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,3154.0,NaN,NaN,". Precioso piso en venta en Torrejón De Ardoz,...",zona_suroeste,zona_suroeste,NaN
15895,piso-zona_suroeste-65871635784_100500,265000.0,piso,NaN,NaN,En buen estado,NaN,4ª,2.0,1.0,AM260234,Entre 20 y 30 años,73.0,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,Cocina amueblada,True,1,1,NaN,NaN,NaN,NaN,NaN,Suroeste,Gas natural,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Frío,NaN,NaN,NaN,NaN,Entre 60 y 80 €,NaN,3630.0,NaN,NaN,. Agora gestores inmobiliarios vende inmueble ...,zona_suroeste,zona_suroeste,NaN
15896,piso-zona_suroeste-65909234569_993874,278600.0,piso,NaN,40.0,NaN,NaN,Bajo,1.0,1.0,09-MAD-01819,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6965.0,NaN,NaN,. Oportunidad Bancaria para Inversores en Comp...,zona_suroeste,zona_suroeste,NaN
15897,piso-zona_suroeste-65928438416_100500,278600.0,piso,NaN,NaN,NaN,NaN,Bajo,1.0,1.0,MD01113274/6260,Entre 20 y 30 años,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Otra compañía,Aluminio,Suroeste,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,6965.0,NaN,NaN,. Venta de piso de 40 m2 en Torrejón de Ardoz....,zona_suroeste,zona_suroeste,NaN
15898,piso-zona_suroeste-66678184201_100500,238000.0,piso,NaN,NaN,En buen estado,NaN,3ª,3.0,1.0,2201/22010082/1,NaN,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,2833.0,NaN,NaN,". ESTUPENDA VIVIENDA EN VENTA, SIN COMISIONES ...",zona_suroeste,zona_suroeste,NaN